apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: papp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papp
  template:
    metadata:
      labels:
        app: papp 
    spec:
      containers:
      - name: nodeserver
        image: marchinawi/papp:latest
        ports:
        - containerPort: 5000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31110
